# Generated by Django 3.1 on 2020-08-15 17:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('submitted_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('attribution_url', models.TextField(blank=True, default='')),
                ('attribution_text', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('PUB', 'Published'), ('REV', 'In Review'), ('REM', 'Removed')], default='REV', max_length=3)),
            ],
        ),
    ]
